### ISSUE TITLE
如何删除 标签

### ISSUE THREAD

**Issue by george-wyy** [hysasuke/Project-Hub#1]
您好，使用您的工具，很有趣，
但发现不能删除标签，请问是有什么方法可以删除。
另外，想问您这个系统，是本地运行的吗？

**Comment by hysasuke** [comment]
是本地运行的，但是在创建链接快捷方式的时候会从目标网站抓取图标信息。

删除标签具体是指删除分组，还是删除分组里面的快捷方式呢？
不过通过右上角菜单里的Edit按钮，则可以进入编辑模式，就可以删除分组还有快捷方式了。同时也可以拖拽进行排序

**Comment by hysasuke** [comment]
> 您好，使用您的工具，很有趣， 但发现不能删除标签，请问是有什么方法可以删除。 另外，想问您这个系统，是本地运行的吗？


是本地运行的，但是在创建链接快捷方式的时候会从目标网站抓取图标信息。

删除标签具体是指删除分组，还是删除分组里面的快捷方式呢？
不过通过右上角菜单里的Edit按钮，则可以进入编辑模式，就可以删除分组还有快捷方式了。同时也可以拖拽进行排序

**Comment by george-wyy** [comment]
好嘞，找到编辑模式了，谢谢您~
